spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/registry
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  expiration-seconds: 3600
  issuer: ${spring.application.name}