spring:
  application:
    name: docker-registry
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/registry
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
server:
  port: 5000
app:
  clear-uploads:
    cron: 0 0 * * * *
    ttl-minutes: 60